[package]
edition = "2021"
name = "lsp-server"
version = "0.5.2"
authors = ["rust-analyzer developers"]
repository = "https://github.com/rust-analyzer/lsp-server"
license = "MIT OR Apache-2.0"
description = "Generic LSP server scaffold."

[workspace]
members = ["xtask"]

[dependencies]
log = "0.4.3"
serde_json = "1.0.34"
serde = { version = "1.0.83", features = ["derive"] }
crossbeam-channel = "0.5.4"

[dev-dependencies]
lsp-types = "0.93.0"
